name: Docker Build Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t tms-vault:latest .

      - name: Verify Docker image build
        run: |
          docker images tms-vault:latest